services:
  web:
    build: .
    command: >
      sh -c "redis-server --daemonize yes && 
              poetry run python manage.py migrate && 
              poetry run uvicorn myapp.asgi:application --host 0.0.0.0 --port 8000 --workers 4 --proxy-headers"
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A myapp worker --loglevel=info --concurrency=5
    volumes:
      - .:/app
    depends_on:
      - redis
